os: linux
language: python
python:
    - "3.6"
    - "3.7"
    - "3.8"
    - "3.9-dev"
    - "3.10-dev"
install:
    - pip install tox-travis
    - pip install codecov
script: tox
env:
    - POST_COMMAND=codecov
